# Generated by Django 4.1.6 on 2023-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='게시물 제목', max_length=50)),
                ('content', models.TextField(help_text='게시물 내용')),
                ('update_dttm', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('create_dttm', models.DateTimeField(help_text='생성 시간')),
            ],
        ),
    ]
